[platformio]
default_envs = cyd

[env:cyd]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
board_build.mcu = esp32
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

monitor_speed = 115200

build_flags =
    -Ilib/TFT_eSPI_Config

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bodmer/TFT_eWidget @ 0.0.6
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    tzapu/WiFiManager @ ^2.0.17
    https://github.com/PaulStoffregen/Time.git

[env:cyd-sim]
platform = espressif32 @ 6.9.0
board = esp32dev
framework = arduino
board_build.mcu = esp32
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
build_flags =
    -Ilib/TFT_eSPI_Config
    -DSIMULATE_SCALES
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bodmer/TFT_eWidget @ 0.0.6
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    tzapu/WiFiManager @ ^2.0.17
    https://github.com/PaulStoffregen/Time.git
